import 'normalize.css';
import './globals.css';
import { Fira_Code, Poppins } from 'next/font/google';

const fira = Fira_Code({
  subsets: ['latin'],
  variable: '--font-fira',
});

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: '400',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${fira.variable} ${poppins.variable} bg-green_bg`}>
        {children}
      </body>
    </html>
  );
}
